### ISSUE TITLE
你好大佬，请教下我想使用您制作的NanoHatOLED编译固件Lienol/openwrt

### ISSUE THREAD

**Issue by tudi1909** [vinewx/NanoHatOLED#1]
按照上述提示，配置好后（ Python2.7的环境），屏幕并不能点亮
不知道如何解决
感谢！

**Comment by vinewx** [comment]
1. 通过ssh登录路由器，输入以下命令，查看是否成功编译进去
`opkg list nanohatoled`
2. 为了防止烧屏，10秒不操作会自动息屏，可通过按键点亮。
3. python2.7版不支持天气信息，按[Enable weather info / 显示天气](https://github.com/vinewx/NanoHatOLED#enable-weather-info--%E6%98%BE%E7%A4%BA%E5%A4%A9%E6%B0%94-python3)操作也会导致不亮屏
4. 第三方固件源码可能缺少软件依赖i2c-tools、python-pillow / python3-pillow、python-smbus / python3-smbus，建议编译时更换官方软件源或者使用OpenWrt、FriendlyWrt官方源码编译固件。
5. 可以直接使用我预编译好的固件[NanoWrt](https://github.com/vinewx/NanoWrt)

**Comment by tudi1909** [comment]
> * 通过ssh登录路由器，输入以下命令，查看是否成功编译进去
>   `opkg list nanohatoled`
> * 为了防止烧屏，10秒不操作会自动息屏，可通过按键点亮。
> * python2.7版不支持天气信息，按[Enable weather info / 显示天气](https://github.com/vinewx/NanoHatOLED#enable-weather-info--%E6%98%BE%E7%A4%BA%E5%A4%A9%E6%B0%94-python3)操作也会导致不亮屏
> * 第三方固件源码可能缺少软件依赖i2c-tools、python-pillow / python3-pillow、python-smbus / python3-smbus，建议编译时更换官方软件源或者使用OpenWrt、FriendlyWrt官方源码编译固件。
> * 可以直接使用我预编译好的固件[NanoWrt](https://github.com/vinewx/NanoWrt)

感谢明示，我再试试

**Comment by tudi1909** [comment]
已解决
