### ISSUE TITLE
此APP适配什么系统呢？

### ISSUE THREAD

**Issue by GBCDF** [vinewx/NanoHatOLED#2]
你好，在openwrt 19.07上，使用python3编译，驱动不了oled，使用python2.7，19.07编译错误。

此app适配官方源的openwrt不？  还是只适配friendlywrt？

谢谢

**Comment by vinewx** [comment]
仅适用于[NanoHatOLED扩展版](https://wiki.friendlyarm.com/wiki/index.php/NanoHat_OLED)硬件；
无系统限制。OpenWrt官方源主分支移除python2.7支援，所以无法编译；
建议使用预编译好的固件：https://github.com/vinewx/NanoWrt/releases

**Comment by GBCDF** [comment]
你好，我的设备还是不能正常工作，再请教：
NanoPi NEO2 + NanoHatOLED，OpenWrt SNAPSHOT v19.07.3，20200904编译，没有同时编译NanoHatOLED。
安装预编译好的nanohatoled_1.0.4-1_py2.7_all.ipk，OpenWrt提示无法安装相关python2.7依赖。

我上一个编译的版本，是同时编译了NanoHatOLED的，选用python3.x，但是屏幕没反映。/etc/init.d/nanohatoled restart也没反映。
这是我的编译脚本，请大佬帮我看看，这样编译对不？

#!/bin/bash
mkdir neo2 && cd neo2
git clone https://git.openwrt.org/openwrt/openwrt.git ./
sed -i '$a src-git NanoHatOLED https://github.com/vinewx/NanoHatOLED.git' ./feeds.conf.default
./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a
make menuconfig 
(基础Luci配置外，Extra packages -> nanohatoled，依赖i2c-tools、python3-pillow、python3-smbus自动选中了的）
make download -j8 V=s
make toolchain/install -j$(nproc) V=s
make -j$(nproc) V=s

万分感谢！

**Comment by vinewx** [comment]
请提供你编译好的固件以便于排查问题

**Comment by GBCDF** [comment]
https://ctm.dhobi.win/openwrt-sunxi-cortexa53-friendlyarm_nanopi-neo2-ext4-sdcard.img.gz
默认IP：192.168.1.11
固件包含：Luci、theme-argon、passwall、NanoHatOLED

请大佬有空帮我看看这个固件，谢。

**Comment by vinewx** [comment]
官方源i2c故障，非个例
参考资料：
1. [Orange Pi Zero: No /dev/i2c-0 device](https://forum.openwrt.org/t/orange-pi-zero-no-dev-i2c-0-device/51969)
2. [I built linkit7688 v19.07.2 and get SMBus(busnum) FileNotFoudError](https://forum.openwrt.org/t/i-built-linkit7688-v19-07-2-and-get-smbus-busnum-filenotfouderror/59595)

建议:
1. 尝试上面帖子所述解决方案；
2. 尝试使用[Lienol/openwrt](https://github.com/Lienol/openwrt)、[Lean/lede](https://github.com/coolsnowwolf/lede)、[friendlywrt](https://github.com/friendlyarm/friendlywrt) 进行编译；
3. FriendlyWrt编译方法可参考https://github.com/vinewx/NanoWrt/blob/master/.github/workflows/neo2_friendlywrt.yml

**Comment by GBCDF** [comment]
谢谢大佬，该问题可以关闭了哈。
我一直计划，在官方源最新代码上进行编译，但NEO2驱动不了oled、系统内显示不了cpu频率和温度，参考各种资料修改dts均不行。
最后使用杂交的方式，使用FriendlyWrt和openwrt官方源混合编译，Kernel:4.14.11 + 最新的openwrt程序，需要的功能都实现了。
